### PR TITLE
Run React, Express App Using Docker

### PR DESCRIPTION
**Pull request by vigneshshettyin**

### CODE REVIEW

**Comment by ajeetraina** [comment]
Hello @vigneshshettyin Thanks for contributing the tutorial. 
I would suggest to create a new Eventhandbook and put these contents under that.

For Example: I created a new "React, Express and Docker" page for you to put all your contents into it.


Sample Handbooks:
- Docker for .NET - https://contribute.docker.com/docs/communityleaders/eventhandbooks/dotnet/
- Go - https://contribute.docker.com/docs/communityleaders/eventhandbooks/go/
- Docker for Beginners - https://contribute.docker.com/docs/communityleaders/eventhandbooks/docker101/

**Comment by vigneshshettyin** [comment]
> Hello @vigneshshettyin Thanks for contributing the tutorial.
> I would suggest to create a new Eventhandbook and put these contents under that.
> 
> For Example: I created a new "React, Express and Docker" page for you to put all your contents into it.
> 
> Sample Handbooks:
> 
> * Docker for .NET - https://contribute.docker.com/docs/communityleaders/eventhandbooks/dotnet/
> * Go - https://contribute.docker.com/docs/communityleaders/eventhandbooks/go/
> * Docker for Beginners - https://contribute.docker.com/docs/communityleaders/eventhandbooks/docker101/

Hey, @ajeetraina Thanks for the response. Will do it.

**Comment by ajeetraina** [comment]
Please add it here https://contribute.docker.com/docs/communityleaders/eventhandbooks/react/

**Comment by vigneshshettyin** [comment]
> Please add it here https://contribute.docker.com/docs/communityleaders/eventhandbooks/react/

Hey, @ajeetraina I have updated.

**Review by rexdivakar — APPROVED** [review]

**Comment by ajeetraina** [comment]
Thanks @vigneshshettyin for the valuable contribution. Thanks @rexdivakar for your time in reviewing it.

**Pull request merged**
